//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/10/2022 5:19:24 μμ
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DxBlazorApplication1
{
    public partial class XAF_User {

        public XAF_User()
        {
            this.IsActive = true;
            this.XAF_Roles = new List<XAF_Role>();
            OnCreated();
        }

        public virtual int ID { get; set; }

        public virtual string? UserName { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual bool ChangePasswordOnFirstLogon { get; set; }

        public virtual string? StoredPassword { get; set; }

        public virtual int? PARTY_ID { get; set; }

        public virtual string? ENERGOI_USER { get; set; }

        public virtual int? OBJECT_ID { get; set; }

        public virtual int? CURRENT_TASK_ID { get; set; }

        public virtual DateTime? START_TIME { get; set; }

        public virtual int? CURRENT_APPOINTMENT_ID { get; set; }

        public virtual int? PROJECT_ID { get; set; }

        /// <summary>
        /// The Facility where the user accepts Appointments
        /// </summary>
        public virtual int? APPOINTMENT_FACILITY_ID { get; set; }

        public virtual IList<XAF_Role> XAF_Roles { get; set; }

        public virtual XAF_Users_Web_Detail XAF_Users_Web_Detail { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
