//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/10/2022 5:19:24 μμ
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DxBlazorApplication1
{
    public partial class XAF_Users_Web_Detail {

        public XAF_Users_Web_Detail()
        {
            OnCreated();
        }

        public virtual int ID { get; set; }

        public virtual string? FULL_NAME { get; set; }

        public virtual string? COMPANY { get; set; }

        public virtual string? ADDRESS { get; set; }

        public virtual string? EMAIL { get; set; }

        public virtual string? TEL1 { get; set; }

        public virtual string? TEL2 { get; set; }

        public virtual Guid GUID { get; set; }

        public virtual int? UPLOADED_FILE_ID { get; set; }

        public virtual string? SPECIALIZATION { get; set; }

        public virtual string? FIRST_NAME { get; set; }

        public virtual string? LAST_NAME { get; set; }

        public virtual string? AFM { get; set; }

        public virtual DateTime? DATE_REGISTERED { get; set; }

        public virtual XAF_User XAF_User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
